### ISSUE TITLE
Program will not work.

### ISSUE THREAD

**Issue by dedisystems** [Oky12/ServerManagerForFivem#1]
I was actually quite happy someone came up with the server manager that included a resource list and everything! However, it does not work for me. 
![image](https://user-images.githubusercontent.com/43257146/58851545-ca40d000-8658-11e9-89a6-8f987ee04d64.png)

**Comment by dedisystems** [comment]
I have also tried running for different enviroments such as Windows 08, XP, Etc.

**Comment by dedisystems** [comment]
Also, it is in my server data

**Comment by dedisystems** [comment]
Updated the our server start.bat to say server_start.bat. Now I get a error.
![image](https://user-images.githubusercontent.com/43257146/58852228-5227d980-865b-11e9-81a7-ecf7c522c363.png)

**Comment by Nyako01** [comment]
Did you already instal net. Framework 4.0?

**Comment by dedisystems** [comment]
Yes

**Comment by Nyako01** [comment]
Try do repair or reinstall net. Framework 4.0 or above

**Comment by dedisystems** [comment]
I tried it in 3 completely different server enviroments.. All 3 have 4.0+
.net and all 3 of them run into the same error. I do have my bat, cfgs, and
your server manager located in my server folder.

**Comment by Nyako01** [comment]
this is weird. I have tested it on my private server and it works without problems.

by the way. What windows do you use?
and what build?

**Comment by dedisystems** [comment]
I use the most updated windows 10 and and a up to date windows 2012r2
dedicated machine I'll get the builds tomorrow as its 5am for me.

**Comment by Nyako01** [comment]
Build 1903?
And what version your using?. Pro?

**Comment by Nyako01** [comment]
try this upcoming version
[FivemServerManager_1.1.zip](https://github.com/Oky12/FivemServerManager/files/3251663/FivemServerManager_1.1.zip)

**Comment by driftonez** [comment]
same issue but on windows server 2016 r2, doesnt launch, also doesnt launch on windows 10 on my personal rig, copied your requirements

**Comment by Nyako01** [comment]
@driftonez requirements only net. Framework 4.0. file server.cfg and file start_server.bat

**Comment by driftonez** [comment]
thats already on both of my systems and nothing, im watching the background proccess pick up the program but shuts down immediately.

**Comment by Nyako01** [comment]
which version do you use?
1.0 or 1.1 (file above)

**Comment by driftonez** [comment]
im running file 1.1 and i tried 1.0 aswell.

**Comment by Nyako01** [comment]
Hmmm.... I don't know how to fix it. Because this tool work normally on my windows 10 pro build 1903.

**Comment by Nyako01** [comment]
And this problem only appears on some user not all user.

**Comment by Nyako01** [comment]
Try reinstal net. Framework 4.0, Or instal all net. Framework version

**Comment by Nyako01** [comment]
make sure this tool added on exclusion in your antivirus or disable your antivirus. because antivirus will be detected this tool as suspicious program

**Comment by driftonez** [comment]
im running net framework 4.6 will that cause any issues at all

**Comment by Nyako01** [comment]
i think not

**Comment by driftonez** [comment]
bugger i cant downgrade without causing issues.

**Comment by alan245245** [comment]
![image](https://user-images.githubusercontent.com/52160239/62375214-5fd0e100-b570-11e9-9d9e-cd97f2558399.png)
The Programme is not responding after a while. I got NET. Framework 4.5 installed already on the Server.
