### ISSUE TITLE
[Feature Request] Kick all button/Resize the menu/Setting on restart(with button to clear cache)

### ISSUE THREAD

**Issue by PERPGamer** [Oky12/ServerManagerForFivem#3]
Basically a button under the Playerlist that you can click to kick everyone on the server. (in case of a modder messing up the server)
Along with a way to make the menu larger, please.
Maybe also a setting when you click restart, it'll auto clear cache

**Comment by Nyako01** [comment]
ok i add that on next update

**Comment by Nyako01** [comment]
i try enable resize function and set all to fit with size windows but is look weird when maximize. here the screenshot

![Screenshot_40](https://user-images.githubusercontent.com/30838114/59516130-dba49a80-8eea-11e9-9e4c-874accacd1f7.png)
![Screenshot_41](https://user-images.githubusercontent.com/30838114/59516147-e3fcd580-8eea-11e9-90f4-56beef391df2.png)
![Screenshot_45](https://user-images.githubusercontent.com/30838114/59516159-eb23e380-8eea-11e9-8533-f1c36adfd560.png)
![Screenshot_42](https://user-images.githubusercontent.com/30838114/59516164-eeb76a80-8eea-11e9-824d-2d12ea2d2eac.png)
![Screenshot_43](https://user-images.githubusercontent.com/30838114/59516173-f24af180-8eea-11e9-87d3-928445dcdb07.png)
![Screenshot_44](https://user-images.githubusercontent.com/30838114/59516178-f6770f00-8eea-11e9-91ce-0e8597b55941.png)


maybe you have a suggestion?

**Comment by Nyako01** [comment]
new version has been release
