### ISSUE TITLE
[BUG] Users with spaces in their name on the PlayerList

### ISSUE THREAD

**Issue by PERPGamer** [Oky12/ServerManagerForFivem#4]
![bug](https://user-images.githubusercontent.com/13124880/59461879-681e6280-8df0-11e9-818d-f30a9adf4a4a.JPG)
The name should be [2P-01] Tyler John

**Comment by Nyako01** [comment]
![Screenshot_39](https://user-images.githubusercontent.com/30838114/59507052-0fc09100-8ed4-11e9-8e5f-f4ec06058d82.png)

I made a note in the Fivem forum about this BUG. so make sure the Steam Name of the player has no space

**Comment by Nyako01** [comment]
I will fix this problem in the next update. for now do according to the notes that I made in the forum

**Comment by Nyako01** [comment]
The bug has been Fixed. i will release next update soon after test all feature

**Comment by Nyako01** [comment]
new version has been release
